Data Type에대해서 알아보자

_만약에 어떤 data type인지 알고 싶으면 class(___)를 console에 입력해보자_












# Vector

벡터끼리 계산하기 매우편하다!

In [ ]:
nums <- c(1,2,3)
#벡터의 이름을 정해줄수도 있다.
names(nums) <- c("first","second","third")
print(nums)

#벡터끼리 계산도 매우 편하다!

more_nums <- c(4,5,6)
print("=========")
nums+more_nums
#벡터안의 value의 합을 찾을수도 있다.
print(sum(nums))


 first second  third 
     1      2      3 
[1] "========="


first second  third 
     5      7      9

[1] 6


**파이썬은 index가 0부터 시작하지만, R에서는 index가 0부터 시작한다!**




In [ ]:
nums[1]

first 
    1

logical comparison도 가능하다


In [ ]:
is_bigger_than_1 <- nums>1
is_bigger_than_1

#위의 logical vector를 이용하여 원하는것만 걸러내자
print(nums[is_bigger_than_1])

first second  third 
 FALSE   TRUE   TRUE

second  third 
     2      3 


# Matrix
matrix는 **같은 data type**(숫자, char, logical)으로만 만들어진 고정된 행렬이다



In [ ]:
#1에서9까지 / 행으로 / 행은 총 3개!
my_matrix<- matrix(1:9,byrow = TRUE, nrow = 3)
my_matrix

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

matrix를 이용한 계산 역시 여러가지가 있다

In [ ]:
#각 행의 합을 구해주자
print(rowSums(my_matrix))
#각 원소에 2를 곱해주자
print(my_matrix*2)


more_matrix <-matrix(11:19, byrow = TRUE, nrow = 3)

#matrix끼리 더할수 있다.
print(my_matrix+more_matrix)



[1]  6 15 24
     [,1] [,2] [,3]
[1,]    2    4    6
[2,]    8   10   12
[3,]   14   16   18
     [,1] [,2] [,3]
[1,]   12   14   16
[2,]   18   20   22
[3,]   24   26   28


행끼리의 곱셈은 살짝 조심해주자!

In [ ]:
#같은 위치의 원소끼리만 곱할때
print(my_matrix * more_matrix)

#일반적인 행렬사 끼리의 곱을 할때
print(my_matrix %*% more_matrix)

     [,1] [,2] [,3]
[1,]   11   24   39
[2,]   56   75   96
[3,]  119  144  171
     [,1] [,2] [,3]
[1,]   90   96  102
[2,]  216  231  246
[3,]  342  366  390


# Factors

factor는 categorical varaiable을 저장할때 쓰인다

먼저 예시를 봐보면


In [ ]:
speed_vector<- c("fast","slow","fast","fast","fast","slow","medium")
speed_factor <- factor(speed_vector)
print(speed_factor)

[1] fast   slow   fast   fast   fast   slow   medium
Levels: fast medium slow


R은 variable이 continuous인지 categorical인지 자동으로 알아낸다

categorical variable도 종류가 나뉘는데


*   nomial : 순서가 없는것
*   ordinal :  순서가 있는것

위의 speed_vector를 보면 빠르고 느린것에는 순서가 있으므로 ordinal일테고

*사자/호랑이/코끼리*  같은 경우에는 nomial이다




In [ ]:
#summary를 통해서 level별로 몇개인지 알아보자
summary(speed_factor)

#ordered factor를 만들고 싶으면
ordered_speed_factor<- factor(speed_vector, ordered = TRUE, levels = c("slow","medium","fast"))
summary(ordered_speed_factor)

fast medium   slow 
     4      1      2

slow medium   fast 
     2      1      4

# Data frame
 Data frame 은 matrix와는 다르게 여러 종류의 data type를 저장할수 있다

 Data frame을 만들대는 vector를 넣어주게 되는데 이때 vector하나가 열 하나가 되는것이다

 



In [ ]:
col_1 <- c("a","b","c")
col_2 <- c(1,2,3)
col_3 <- c(TRUE, TRUE, FALSE)

my_df <- data.frame(col_1,col_2,col_3)
print(my_df)

#df에서 선택하기

#열 선택하기
print(my_df[,1])
 #열선택하는 다른 방법!
print(my_df$col_1)
 #행 선택하기
print(my_df[1,])

#특정을 선택하기
is_bigger_than_2 = col_2>2

my_df.subset <- subset(my_df, subset = is_bigger_than_2)
print(my_df.subset)

  col_1 col_2 col_3
1     a     1  TRUE
2     b     2  TRUE
3     c     3 FALSE
[1] a b c
Levels: a b c
[1] a b c
Levels: a b c
  col_1 col_2 col_3
1     a     1  TRUE
  col_1 col_2 col_3
3     c     3 FALSE


# 정렬 (sort)

order()을 이용하자

order를 이용하면 반환되는 값은 value의 ranked position 이다  _밑에 예시를 잘보쟈_


In [ ]:
#먼저 앞으로 쓰일 data frame을 만들어보자
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

# Create a data frame from the vectors
planets_df <- data.frame(name, type, diameter, rotation, rings)

In [ ]:
order(diameter)

[1] 1 4 2 3 8 7 6 5

그래서 바로 쓰면안되고 index로 넣어야한다

In [ ]:
diameter[order(diameter)]

[1]  0.382  0.532  0.949  1.000  3.883  4.007  9.449 11.209

data frame에 사용할때도 조심하자!


In [ ]:
positions<- order(diameter)
planets_df[positions]

ERROR: ignored

In [ ]:
#현재 positions는 순위가 저장되어있으니까 순위를 row에 넘겨줘야한다
planets_df[positions,]

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
8 Neptune Gas giant           3.883      0.67   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
5 Jupiter Gas giant          11.209      0.41   TRUE

# List
List는 다양한 object를 순서대로 넣을수 있는 data type

위에서는 길이에 신경을 써야하는 경우가 많았는데, list는 신경쓰지 않아도 된다.

사실상 어떤걸 넣어도 상관없는게 list다!

먼저 코드를 한번 봐보자



In [ ]:
anything_list <- list( nums, my_matrix, planets_df)
anything_list

[[1]]
 first second  third 
     1      2      3 

[[2]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[3]]
     name               type diameter rotation rings
1 Mercury Terrestrial planet    0.382    58.64 FALSE
2   Venus Terrestrial planet    0.949  -243.02 FALSE
3   Earth Terrestrial planet    1.000     1.00 FALSE
4    Mars Terrestrial planet    0.532     1.03 FALSE
5 Jupiter          Gas giant   11.209     0.41  TRUE
6  Saturn          Gas giant    9.449     0.43  TRUE
7  Uranus          Gas giant    4.007    -0.72  TRUE
8 Neptune          Gas giant    3.883     0.67  TRUE

정말로 아무거나 넣을수 있고, 내가 넣은 순서대로 저장이된다

_물론 진짜 아무거나 넣는다기보다는 내가 원하는 자료들을 제약 없이 넣고 싶을때 쓰면될거 같다_


list를 부를때는 위에서와 같이 $를 쓰거나 [[]]를 이용하면된다.


In [ ]:
#먼저 name을 해서 이름을 정해주자 
names(anything_list) <- c("numbers","matrix","planet_df")
anything_list

$numbers
 first second  third 
     1      2      3 

$matrix
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

$planet_df
     name               type diameter rotation rings
1 Mercury Terrestrial planet    0.382    58.64 FALSE
2   Venus Terrestrial planet    0.949  -243.02 FALSE
3   Earth Terrestrial planet    1.000     1.00 FALSE
4    Mars Terrestrial planet    0.532     1.03 FALSE
5 Jupiter          Gas giant   11.209     0.41  TRUE
6  Saturn          Gas giant    9.449     0.43  TRUE
7  Uranus          Gas giant    4.007    -0.72  TRUE
8 Neptune          Gas giant    3.883     0.67  TRUE

In [ ]:
#이제는 $로해서 선택할수있다
anything_list$planet_df

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
8 Neptune Gas giant           3.883      0.67   TRUE

In [ ]:
#숫자로 index할때는 조심하자!
anything_list[1]

$numbers
 first second  third 
     1      2      3

In [ ]:
anything_list[[1]]

first second  third 
     1      2      3

다시한번 정리를하면


*   vector일때는 []
*   list일때는 [[]]



를 이용하여 선택한다!