이전에는 Data Type과 관련된 얘기가 많았다면
 이번에는 그 외에 기본적으로 알고 있어야하는 R의 기능들을 더 정리해 보았다. **굵은 텍스트**

## Conditionals과 Control Flow

예시를 통해 알아보자

In [ ]:
TRUE == 1

[1] TRUE

알파벳끼리 비교를 할때에는 알파벳의 뒤일수록 큰것이다


In [ ]:
"abc">"def"

[1] FALSE

In [ ]:
"a"<"c"

[1] TRUE

vector 혹은 matrix내에도 쓰일수있다.

In [ ]:
nums <- c(16,9,13,5,17,14)

nums==13

[1] FALSE FALSE  TRUE FALSE FALSE FALSE

In [ ]:
nums.matrix <- matrix(c(nums),nrow=2)
nums.matrix ==13


[,1]  [,2]  [,3] 
[1,] FALSE  TRUE FALSE
[2,] FALSE FALSE FALSE

&랑 |를 쓸수도 있다!


In [ ]:
select <- nums>10 & nums<15
#조건에 해당하는 원소의 개수?
print(select)

#조건에 해당하는 숫자만 print하기
print(nums[select])

[1] FALSE FALSE  TRUE FALSE FALSE  TRUE
[1] 13 14


## Loop

R 에서도 당연히 for loop을 이용할 수 있다!
생김새도 python이랑 비슷한데 괄호에서 차이가 있다


바로 예시로 가보자

In [ ]:
for (num in nums){
  print(num)
}

[1] 16
[1] 9
[1] 13
[1] 5
[1] 17
[1] 14


# Tip!

잘 모르는 함수가 나올때는 앞에 ?를 붙여보자

그리고 만약에 argument만 알고 싶다면 args(?)로 해주자



In [ ]:
?sd

In [ ]:
args(sd)

function (x, na.rm = FALSE) 
NULL

# Function 만들기

R에서 function을 만들때에는


my_fun <- function(arg1, arg2) {
  body
}

의 형식으로 만들면된다

이때 값을 넘길때에는 **call by value**이다



---

##### function은 return을 따로 적을 필요없이 마지막 줄에 return 하고 싶은 object를 적어주면된다.


In [ ]:
triple<- function(x){
  x<-3*x
  print(x)
  x
}

In [ ]:
a<-5
triple(a)

#단 R에서도 역시 call by value로 쓰고있다는점은 조심하자!
print(a)

[1] 15


[1] 15

[1] 5


# lapply

function을 list혹은 vector에 apply하는것이다

바로 예시를 봐조자

In [ ]:
test <-c(1,2,3)

multiply<- function(x,howmuch){
  x*howmuch
}

#lapply를 적용해보면
lapply(test, multiply, howmuch = 3)

[[1]]
[1] 3

[[2]]
[1] 6

[[3]]
[1] 9

In [ ]:
class(lapply(test, multiply, howmuch = 3))

[1] "list"

list 형태로 return하는것을 볼수 있다

이게만약에 싫으면 unlist해주면된다


In [ ]:
print(unlist(lapply(test, multiply, howmuch = 3)))
class(unlist(lapply(test, multiply, howmuch = 3)))

[1] 3 6 9


[1] "numeric"

# sapply
위의 과정을 매번하기 귀찮을때는 s(imple)apply를 해주면된다

In [ ]:
sapply(test, multiply, howmuch = 3)
class(sapply(test, multiply, howmuch = 3))

[1] 3 6 9

[1] "numeric"

# vapply
그런데 사실 lapply를 하기에는 손이 너무 많이 가고 sapply를 하니까 너무 이상하게 simplify가 될때에는 **vapply를 이용해서 내가 어떤 형식으로 return해주고 싶은지 argument에서 정해주면된다.**

In [ ]:
extremes<- function(x){
  c(min = min(x), max = max(x))
}
print(nums)

[1] 16  9 13  5 17 14


In [ ]:
print(lapply(nums,extremes) )
print(sapply(nums,extremes))

[[1]]
min max 
 16  16 

[[2]]
min max 
  9   9 

[[3]]
min max 
 13  13 

[[4]]
min max 
  5   5 

[[5]]
min max 
 17  17 

[[6]]
min max 
 14  14 

    [,1] [,2] [,3] [,4] [,5] [,6]
min   16    9   13    5   17   14
max   16    9   13    5   17   14


lapply와 sapply가 조금 다른데, vapply를 통해 내가 원하는게 뭔지 정확히 명시해주자!


In [ ]:
print(vapply(nums,extremes,c(numeric(1),numeric(1))))

    [,1] [,2] [,3] [,4] [,5] [,6]
min   16    9   13    5   17   14
max   16    9   13    5   17   14


# is.  as.

*   is : __가 맞나?

*   as : __로 바꿔라

근데 개인적으로는 그냥 class를 써서 무슨 타입인지 보는게 나은거같다



In [ ]:
li <- list("a","b")
li

[[1]]
[1] "a"

[[2]]
[1] "b"

In [ ]:
is.list(li)

[1] TRUE

In [ ]:
print(unlist(li))
is.vector(unlist(li))

[1] "a" "b"


[1] TRUE

# appendm, rev

In [ ]:
seq1 <- seq(1,10, by=3)
seq1
seq2 <- seq(1200,900, by=-100)
seq2

[1]  1  4  7 10

[1] 1200 1100 1000  900

In [ ]:
merged <- append(seq1,seq2)
merged

[1]    1    4    7   10 1200 1100 1000  900

In [ ]:
merged<- append(merged,rev(merged))
print(merged)

 [1]    1    4    7   10 1200 1100 1000  900  900 1000 1100 1200   10    7    4
[16]    1


# grep, grepl
string에서 pattern을 찾을때 쓰는 function이다

> grepl의 l은 logical의 l이다





---


*여기서 쓰이는 grep은 간단한 "찾기"에는 도움되지만 좀더 복잡한 pattern 을 찾기위해선는 stringr 패키지의 도움을 받아야한다.*

*나중에 string관련해서는 더 자세히 정리할거다*

In [ ]:
animals<- c("cat","moose","ant","tiger")
my_pattern<- grepl(pattern = "a", x=animals)

animals[my_pattern]

[1] "cat" "ant"

In [ ]:
my_position <- grep(pattern = "a", x=animals)
my_position

[1] 1 3

# sub, gsub
위의 grep은 찾는거였다면
sub은 substitute의 s이다, 즉 대체해줄것이다!

In [ ]:
#모든 모음을 _로 바꿔보자
gsub(pattern = "a|e|i|o|u", replacement = "_", x= animals)

[1] "c_t"   "m__s_" "_nt"   "t_g_r"